#!/usr/bin/env sh

xset s 300 5
xss-lock -l -- xsecurelock &
xwallpaper --stretch
eww daemon --restart
eww open bar_1
ibus-daemon --replace --daemonize --restart --xim

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#d0bfff'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Spotify desktop='^3'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
