[shell_alias]
jq = "jaq"

[tools]
chezmoi = "latest"
fnox = "latest"
ripgrep = "latest"
ruff = "latest"
usage = "latest"
biome = "latest"
uv = "latest"
starship = "latest"
bat = "latest"
fd = "latest"
aube = "latest"
node = "lts"
rtk = "latest"
jaq = "latest"
zoxide = "latest"
"github:reemus-dev/gitnr" = "latest"
neovim = "latest"
"github:ataleckij/claude-chats-delete" = "latest"
"conda:git" = "latest"
"conda:yt-dlp" = "latest"
"conda:ffmpeg" = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
"conda:gnupg" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"conda:socat" = "latest"
"conda:openssh" = "latest"
"conda:curl" = "latest"
eza = "latest"
bottom = "latest"
git-lfs = "latest"
"conda:bubblewrap" = "latest"
"conda:rsync" = "latest"
hk = "latest"
deno = "latest"
